[build]
  command = "npm run build"
  publish = "dist"
  base = "MERN_STACK_RESTAURANT_RESERVATION-main/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-api-url.com"
